mutation Login(
  $email: String,
  $password: String
) {
  login(
    email: $email,
    password: $password
  ) {
    statusCode
    accessToken
    refreshToken
    user {
      _id
      email
      phone
      dob
      address {
        state
      }
      heard_about_us
      profile_picture
      sys_dateCreated
      sys_dateModified
      sys_deleted
      sys_userCreated_id
      sys_userCreatedName
      sys_userModified_id
      sys_userModifiedName
      last_login
      role
    }
  }
}


