mutation SignUp(
  $first_name: String,
  $last_name: String,
  $username: String,
  $email: String,
  $address: AddressInput,
  $dob: String,
  $phone: String,
  $heard_about_us: String,
  $profile_picture: String
  ) {
  signUp(
    first_name: $first_name,
    last_name: $last_name,
    username: $username,
    email: $email,
    address: $address,
    dob: $dob,
    phone: $phone,
    heard_about_us: $heard_about_us,
    profile_picture: $profile_picture
    ) {
    statusCode
    message
    email
    temporarySignupKey
  }
}


